project_id = "zvzmnqcbmhpddrpfjrzr"

[functions.generate-wompi-signature]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.google-drive-proxy]
verify_jwt = false

[functions.google-drive-upload]
verify_jwt = false

[functions.google-drive-auth]
verify_jwt = false