// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvzmnqcbmhpddrpfjrzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2em1ucWNibWhwZGRycGZqcnpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MjAzMTUsImV4cCI6MjA3MjA5NjMxNX0.WSAO51Wziybu9k0Ji5WGPUXEC_4RSVYErvamBoWvv7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});